# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='student.proto',
  package='overview_example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rstudent.proto\x12\x10overview_example\x1a\x1egoogle/protobuf/wrappers.proto\"\xa9\x01\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\r\x12*\n\x04name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\x06grades\x18\x03 \x03(\x0b\x32%.overview_example.Student.CourseGrade\x1a/\n\x0b\x43ourseGrade\x12\x11\n\tcourse_id\x18\x01 \x01(\t\x12\r\n\x05grade\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_STUDENT_COURSEGRADE = _descriptor.Descriptor(
  name='CourseGrade',
  full_name='overview_example.Student.CourseGrade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='course_id', full_name='overview_example.Student.CourseGrade.course_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grade', full_name='overview_example.Student.CourseGrade.grade', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=237,
)

_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='overview_example.Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='overview_example.Student.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='overview_example.Student.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grades', full_name='overview_example.Student.grades', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STUDENT_COURSEGRADE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=237,
)

_STUDENT_COURSEGRADE.containing_type = _STUDENT
_STUDENT.fields_by_name['name'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_STUDENT.fields_by_name['grades'].message_type = _STUDENT_COURSEGRADE
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), dict(

  CourseGrade = _reflection.GeneratedProtocolMessageType('CourseGrade', (_message.Message,), dict(
    DESCRIPTOR = _STUDENT_COURSEGRADE,
    __module__ = 'student_pb2'
    # @@protoc_insertion_point(class_scope:overview_example.Student.CourseGrade)
    ))
  ,
  DESCRIPTOR = _STUDENT,
  __module__ = 'student_pb2'
  # @@protoc_insertion_point(class_scope:overview_example.Student)
  ))
_sym_db.RegisterMessage(Student)
_sym_db.RegisterMessage(Student.CourseGrade)


# @@protoc_insertion_point(module_scope)
